@extends('layouts.app')
@section('title','Politique')
@section('content')
<div class="container mt-5">
    <h3 class="mb-4 text-warning">Terms & Conditions</h3>
    <h5 class="m-2 text-warning">Introduction</h5>
    <p class="m-2 mb-4 text-warning">These terms and conditions apply to the website and all its divisions, subsidiaries, and affiliated websites that reference these terms and conditions by reference. By visiting the site, the customer acknowledges acceptance of these terms and conditions. If you do not agree, you should not use this site. The site administrators reserve the right to change, modify, add information, or delete parts of the terms and conditions of use at any time. Changes will take effect upon posting on the site without prior notice. Please regularly check the terms and conditions for updates. Your continued use of the site after the posting of modifications to these terms and conditions of use constitutes your full acceptance of these modifications.
    </p>

    <h5 class="m-2 text-warning">Website Use</h5>
    <p class="m-2 mb-4 text-warning">To visit this site, you must be at least 18 years old or visit the site under the supervision of a parent or legal guardian. We grant you a non-transferable and revocable license to use the Site under the specified terms and conditions. This license is for the purpose of purchasing personal items sold on the site. Commercial use or use on behalf of a third party is prohibited without our explicit and transparent prior authorization. Any violation of these Terms and Conditions will result in the immediate revocation of the license granted in this paragraph without any prior notice. The content appearing on this site is provided for informational purposes only. Explanations regarding the products expressed on this site belong to the sellers themselves, and we have no involvement with them. Comments or opinions expressed on this site belong to the individual who posted them and therefore do not reflect our opinions. Some associated services and features that may be available on the Site require registration or subscription. If you choose to register or subscribe to such services or related features, you agree to provide accurate and up-to-date information about yourself and to update it in a timely manner in case of changes. Each site user is solely responsible for the proper preservation of passwords and other user account identification methods. The account holder is fully responsible for all activities that occur using their password or account. Additionally, you must inform us of any unauthorized use of your password or account. Under no circumstances will the Site be liable, directly or indirectly or in any manner whatsoever, for any loss or damage of any nature arising from or in connection with your non-compliance with this section. During the registration process, the Customer agrees to receive promotional emails from the Site. You will be able to later cancel this option and not receive any promotional emails by clicking on the link at the bottom of any promotional email.
    </p>

    <h5 class="m-2 text-warning">User Messages</h5>
    <p class="m-2 mb-4 text-warning">All your contributions on the site and/or what you provide us, including but not limited to questions, reviews, comments, and suggestions (collectively, "contributions"), become our sole and exclusive property and do not belong to you in any way. In addition to the rights that apply to any type of contribution, once you share your comments or reviews on the site, you also grant us the right to use the name you display that is directly related to that review, comment, or any other content. You may not use a false email address, pretend to be someone else, or attempt in any other way to deceive us, or any third party, regarding the authenticity or reliability of any Submission. We may delete or modify any message, but we are not obligated to do so.
    </p>

    <h5 class="m-2 text-warning">Order Approval and Price Details</h5>
    <p class="m-2 mb-4 text-warning">Please note that in some cases, an order may not be approved for several reasons. Site administrators reserve the right to refuse or cancel any order for any reason and at any time. Before approving a request, we may ask you to provide additional information or other data to verify something, including but not limited to your phone number and address. We strive to provide the most accurate price information to all users who visit the site. However, errors may sometimes occur, such as in cases where the product price is not correctly specified on the site. Therefore, we reserve the right to refuse or cancel any order. In the event that the price of a product is not accurately stated, we may, at our sole discretion, contact you for instructions or cancel your order and inform you of such cancellation. We have the right to refuse or cancel any order, whether it has been confirmed or debited to your credit card.
    </p>

    <h5 class="m-2 text-warning">Trademarks and Copyrights</h5>
    <p class="m-2 mb-4 text-warning">All intellectual property rights, whether registered or unregistered, on the Site, as well as all information on the content and designs contained on the Site, are our property, including but not limited to text, graphics, software, photos, videos, music, and sounds, as well as their selection and coordination, as well as all software compilations, source codes, and major programs. All Site content is also collectively protected by copyright as a unique work. All rights reserved.
    </p>

    <h5 class="m-2 text-warning">Applicable Law and Judicial Bodies</h5>
    <p class="m-2 mb-4 text-warning">These terms and conditions shall be construed and enforced in accordance with the applicable laws of the country. Each party hereby agrees to submit to the jurisdiction of the country's judicial bodies and waives any objection regarding the venue.
    </p>

    <h5 class="m-2 text-warning">Revocation of Consent</h5>
    <p class="m-2 mb-4 text-warning">In addition to any legal provision or injunction, we may, immediately and without notice, terminate these Terms and Conditions or cancel all or part of your rights granted under the Terms and Conditions. Upon termination of this agreement, you must immediately cease visiting and using the Site, and in addition to any legal or equitable action, we may immediately revoke all passwords or other account identifiers granted to you, and deny any further visits to or use of this Site in whole or in part. Any invalidation of this Agreement will not affect all rights and obligations (including but not limited to payment obligations) of the parties issued before the termination date of the contract. Therefore, you agree that the site administrators will not be liable to you or any other person as a result of the suspension or termination of the service. If you are dissatisfied with this site or any of the terms, conditions, systems, policies, guidelines, or practices of a store regarding how the store is operated, the sole and exclusive action you must take is to cease using the site.
    </p>
</div>
@endsection